#docker-compose.yml (Base)
version: '3.4'
services:
  ler-server:
    image: backend/ler-server:${TAG:-latest}
    build:
      context: ./ler_2_server
      dockerfile: Dockerfile
    depends_on:
      - rust
  
  db:
    image: postgres:latest
    restart: always 
    environment:
      - POSTGRES_USER=username
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=postgres
    ports:
      - 5432:5432

  ler-database:
    image: backend/ler-database:${TAG:-latest}
    build:
      context: ./ler_2_database
      dockerfile: Dockerfile
    depends_on:
      - rust-nightly

  rust-nightly:
    image: rustlang/rust:nightly

  rust:
    image: rust