name: Rust

on:
  push:
    branches: 
     - main
     - release/*
     - feature/*
  pull_request:
    branches: [ main ]
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: docker-compose build --parallel
  frontend:
    runs-on: ubuntu-latest
     steps:
      - uses: actions/checkout@v2
      - name: Build frontend
        uses: actions/setup-node@v1
        with:
          node-version: 15.x
        working-directory: ./DJenz_frontend
        run: npm run dev
          

  
