name: Rust

on:
  push:
    branches: 
     - main
     - release/*
     - feature/*
  pull_request:
    branches: [ main ]
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  server:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: docker-compose build --parallel
  
  frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: 
        uses: actions/setup-node@v1
        with:
          node-version: 15.x
      - name: CI
        working-directory: ./DJenz_frontend
        run: npm ci
      - name  : Build
        working-directory: ./DJenz_frontend
        run: npm run build --if-present
      # - name: Test
      #   working-directory: ./DJenz_frontend
      #   run: npm test
          

  
